env:
  DOCKER_COMPOSE_VERSION: 1.21.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-ce
  - docker-compose --version
  - git submodule update --init --recursive

node_js:
  - "9"
  
install:
  - npm install
  - git submodule foreach --recursive npm install

script:
  - npm test
