version: '3'

networks:
  ticket721-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: ticket721_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
      - MONGODB_USER="ticket721"
      - MONGODB_PASS="ticket721pass"
    command: mongod --smallfiles
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - ticket721-network
  ethereum-rpc:
    image: trufflesuite/ganache-cli:v6.1.3
    container_name: ticket721_ethereum-rpc
    ports:
      - "127.0.0.1:8545:8545"
    networks:
      - ticket721-network
    command: ganache-cli -p 8545 --mnemonic "cross uniform panic climb universe awful surprise list dutch ability label cat"
