version: '3'

networks:
  ticket721-network:
    driver: bridge

services:
  mongodb:
    image: mongo:latest
    container_name: ticket721_mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log
      - MONGODB_USER="ticket721"
      - MONGODB_PASS="ticket721pass"
    volumes:
      - ./mongo_data:/data
    command: mongod --smallfiles
    networks:
      - ticket721-network
  ticket721-cacheserver:
    image: node:carbon
    container_name: ticket721_api
    volumes:
      - ../index.js:/usr/src/app/index.js
      - ../passport:/usr/src/app/passport
      - ../routes:/usr/src/app/routes
      - ../mongoose:/usr/src/app/mongoose
      - ../package.json:/usr/src/app/package.json
    environment:
      - DB_URL=mongodb://ticket721_mongodb/ticket721
    working_dir: /usr/src/app
    ports:
      - 8080:8080
    networks:
      - ticket721-network
    command: bash -c "npm install && npm start"
  ethereum-rpc:
    image: trufflesuite/ganache-cli:latest
    container_name: ticket721_ethereum-rpc
    ports:
      - 8545:8545
    networks:
      - ticket721-network
    command: ganache-cli --mnemonic "cross uniform panic climb universe awful surprise list dutch ability label cat"
